### ISSUE TITLE
Script for standardizing topic names, suggestions for removing topics

### ISSUE THREAD

**Issue by lodeous** [lodeous/gencon-nlp#2]
Script to standardize topic names:
- Capitalization
- Spaces

Any topics that we should remove?

**Comment by clarkedb** [comment]
Depending on how high-level or doctrinal we want the topics to be, I suggest we start with removing the following topics but consider removing more:

> Brigham Young
> Ezra Taft Benson
> Harold B. Lee
> Spencer W. Kimball
> Tabernacle Choir
> Thomas S. Monson
> Wilford Woodruff

The full list of topics is [topics.txt](https://github.com/lodeous/gencon-nlp/files/5999060/topics.txt).
