### ISSUE TITLE
Apply Latent Dirichlet Allocation to dataset

### ISSUE THREAD

**Issue by lodeous** [lodeous/gencon-nlp#5]
We did Latent Dirichlet Allocation (LDA) on presidential speeches as a part of a lab on Gibbs sampling last semester.

Go through the lab code and adapt it to work on our general conference dataset for classifying topics.

See http://acme.byu.edu/wp-content/uploads/2021/01/Gibbs_LDA.pdf for implementation details

**Comment by jbwilkes** [comment]
Select a handful of talks that have a given topic (like prayer, or revelation) and then run gibbs/LDA on that subset to get an accuracy - how many of those talk can our model identify prayer/revelation as a major topic

**Comment by jbwilkes** [comment]
I did gibbs LDA on an individual document, now I need to do on multiple documents and see how I can turn it into a supervised learning task - did it get the correct theme yes or no!
