### ISSUE TITLE
Apply Latent Sematic Analysis to the dataset

### ISSUE THREAD

**Issue by lodeous** [lodeous/gencon-nlp#6]
http://acme.byu.edu/wp-content/uploads/2020/11/LSI-Sklearn.pdf
See this lab.

**Comment by lodeous** [comment]
Potentially see if we can map documents to vectors so we can visualize document space.

**Comment by clarkedb** [comment]
Next steps here are to try this on the entire data collection. This means:

**Comment by clarkedb** [comment]
Next steps here are to try this on the entire data collection. This means:

- [ ] Uses the root `data/` directory
- [ ] Ignore filenames with "meta" in the name
- [ ] Stores the matrix and loads if the matrix has already been created
- [ ] Return the vector associated with a given text being compared against the corpus
