### ISSUE TITLE
Basic Data Visualization

### ISSUE THREAD

**Issue by lodeous** [lodeous/gencon-nlp#7]
How many talks do we have?
Who are the top speakers?
What are the top topics?
etc...

**Comment by jbwilkes** [comment]
I worked on this and think it's sufficient for now. Reopen and comment what ideas you have if you think there is more to be done

**Comment by jbwilkes** [comment]
I worked on this and think it's sufficient for now. Reopen and comment what ideas you have if you think there is more to be done

**Comment by jbwilkes** [comment]
Maybe look at it on an six month basis over time - what are the most popular topics over time
