### ISSUE TITLE
Summary.csv Titles Incorrect

### ISSUE THREAD

**Issue by jbwilkes** [lodeous/gencon-nlp#8]
So I can see something went wrong with the summary CSV like for Elder Eyring from 2018 October: The talk was called "Try,Try,Try" and yet the summary.csv has the title as "Try" only, so I worry that the csv format took off the rest of the title because of the commas in the title. If this isn't fixed it'll make merging the topic data with the text a problem

**Comment by lodeous** [comment]
In the scraper I used commas to break apart different metadata about the talk (like year, speaker, and title). This caused titles with commas to be broken apart. I set a limit on the number of commas its allowed to split on now so it should be parsed correctly. I'll update the relevant data on box.

**Comment by jbwilkes** [comment]
So all the metadata was wrong before this fix? So I can delete that metadata from my local machine? Thanks for looking into this

**Comment by lodeous** [comment]
Not all of the metadata was wrong but we don't know which ones are wrong so yes please delete the old .meta.txt files.
